import { LineChart, Line, BarChart, Bar, PieChart, Pie, Cell, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from 'recharts';

interface ChartData {
  type: string;
  title: string;
  data: Array<{ label: string; value: number }>;
  config?: any;
}

interface FinancialDashboardProps {
  data: {
    latestChart?: ChartData;
  } | null;
}

const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042', '#8884D8'];

export default function FinancialDashboard({ data }: FinancialDashboardProps) {
  if (!data?.latestChart) {
    return (
      <div className="dashboard-empty">
        <h2>📊 Financial Dashboard</h2>
        <p>Charts and visualizations will appear here when generated by the agent.</p>
      </div>
    );
  }

  const { latestChart } = data;
  const chartData = latestChart.data.map((item: any) => ({
    name: item.label,
    value: item.value
  }));

  const renderChart = () => {
    switch (latestChart.type.toLowerCase()) {
      case 'line':
        return (
          <ResponsiveContainer width="100%" height={400}>
            <LineChart data={chartData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />
              <Legend />
              <Line type="monotone" dataKey="value" stroke="#8884d8" strokeWidth={2} />
            </LineChart>
          </ResponsiveContainer>
        );

      case 'bar':
        return (
          <ResponsiveContainer width="100%" height={400}>
            <BarChart data={chartData}>
              <CartesianGrid strokeDasharray="3 3" />
              <XAxis dataKey="name" />
              <YAxis />
              <Tooltip />
              <Legend />
              <Bar dataKey="value" fill="#8884d8" />
            </BarChart>
          </ResponsiveContainer>
        );

      case 'pie':
        return (
          <ResponsiveContainer width="100%" height={400}>
            <PieChart>
              <Pie
                data={chartData}
                cx="50%"
                cy="50%"
                labelLine={false}
                label={(entry) => entry.name}
                outerRadius={120}
                fill="#8884d8"
                dataKey="value"
              >
                {chartData.map((_, index) => (
                  <Cell key={`cell-${index}`} fill={COLORS[index % COLORS.length]} />
                ))}
              </Pie>
              <Tooltip />
            </PieChart>
          </ResponsiveContainer>
        );

      default:
        return <p>Unsupported chart type: {latestChart.type}</p>;
    }
  };

  return (
    <div className="dashboard">
      <h2>📊 {latestChart.title}</h2>
      <div className="chart-container">
        {renderChart()}
      </div>
    </div>
  );
}
